---
- name: AUTH-9230 Configure maximum encryption algorithm rounds
  lineinfile:
    path: /etc/login.defs
    line: '{{ item }} 5000'
    regexp: '^{{ item }}'
    state: present
  with_items:
    - SHA_CRYPT_MIN_ROUNDS
    - SHA_CRYPT_MAX_ROUNDS

- name: AUTH-9328 Default umask    
  lineinfile:
    path: /etc/login.defs
    line: 'UMASK 027'
    regexp: '^UMASK'
    state: present

- name: AUTH-9286 Configure maximum password age
  lineinfile:
    path: /etc/login.defs
    line: 'PASS_MAX_DAYS 365'
    regexp: '^PASS_MAX_DAYS'
    state: present    

- name: AUTH-9286 Configure minumum password age
  lineinfile:
    path: /etc/login.defs
    line: 'PASS_MIN_DAYS 10'
    regexp: '^PASS_MIN_DAYS'
    state: present        