---
- name: Update limits.conf - soft core
  lineinfile:
    path: /etc/security/limits.conf
    line: '* soft core 0'
    regexp: '^\*\s+soft\s+core\s+0$'
    insertbefore: '^#\sEnd\sof\sfile'
    create: yes
    state: present

- name: Update limits.conf - hard core
  lineinfile:
    path: /etc/security/limits.conf
    line: '* hard core 0'
    regexp: '^\*\s+hard\s+core\s+0$'
    insertbefore: '^#\sEnd\sof\sfile'
    create: yes
    state: present    

# ONT-8104 Run 'docker info' to see warnings
- name: Disable IPv4 forwarding by default
  set_fact:
    net_ipv4_conf_all_forwarding: 0

- name: Enable IPv4 forwarding if Docker installed
  set_fact:
    net_ipv4_conf_all_forwarding: 1
  when: "'docker-ce' in ansible_facts.packages"

- name: KRNL-6000 net.ipv6.conf.all.accept_redirects
  sysctl: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { name: kernel.sysrq, value: "0" }
    - { name: net.ipv4.conf.all.forwarding, value: "{{ net_ipv4_conf_all_forwarding }}" }
    - { name: net.ipv4.conf.default.accept_source_route, value: "0" }
    - { name: net.ipv4.conf.all.send_redirects, value: "0" }
    - { name: net.ipv4.conf.default.accept_redirects, value: "0" }
    - { name: net.ipv6.conf.all.accept_redirects, value: "0" }
    - { name: net.ipv6.conf.default.accept_redirects, value: "0" }

