---
- name: LOGG-2154 Enable logging to an external logging host
  template:
    src: 01-remotelog.conf.j2
    dest: /etc/rsyslog.d/01-remotelog.conf
    owner: root
    group: root
    mode: u=rw,g=rw,o=r
  register: logg

- name: Restart rsyslog 
  service:
    name: rsyslog
    state: restarted
  when: logg.changed


  