---
# tasks file for lynis-role
- name: KRNL
  import_tasks: KRNL.yml

- name: PKGS Packages
  import_tasks: PKGS.yml

- name: BANN Banners
  import_tasks: BANN.yml

- name: ACCT Accounting
  import_tasks: ACCT.yml

- name: LOGG Logging
  import_tasks: LOGG.yml

- name: SSH Secure Shell Daemon
  import_tasks: SSH.yml  


- name: AUTH Authentication
  import_tasks: AUTH.yml  