---
# tasks file for lynis-role

# Run packages first so we can use the package_facts in other tasks
- name: PKGS Packages
  import_tasks: PKGS.yml

- name: KRNL
  import_tasks: KRNL.yml

- name: BANN Banners
  import_tasks: BANN.yml

- name: ACCT Accounting
  import_tasks: ACCT.yml

- name: LOGG Logging
  import_tasks: LOGG.yml

- name: SSH Secure Shell Daemon
  import_tasks: SSH.yml

- name: AUTH Authentication
  import_tasks: AUTH.yml

- name: STRG Storage Devices
  import_tasks: STRG.yml

- name: TIME Time Services
  import_tasks: TIME.yml

- name: NETW Networking
  import_tasks: NETW.yml