---
# Purge old packages first so there's no old configs
- name: PKGS-7346 Purge old/removed packages
  package:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_lines:
    - "dpkg --list | grep ^rc | awk '{ print $2; }'"

- name: Gather the package facts - we'll need these later
  package_facts:
    manager: auto

# Debian Specific
- name: PKGS-7370 debsums, PKGS-7394 apt-show-versions, ACCT-9622 acct
  apt:
    name: debsums, apt-show-versions, acct
    state: present

- name: ACCT-9622 acct, ACCT-9626 sysstat, ACCT-9632 auditd, FINT-4350 aide, HRDN-7230 chkrootkit, HRDN-7230 malware scanner, CRYP-8005 psuedo random
  package:
    name: acct, sysstat, auditd, aide, chkrootkit, clamav, clamav-daemon, haveged
    state: present    

- name: ClamAV Daemons Active
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "clamav-daemon"
    - "clamav-freshclam"


- name: HAveged Daemons Active
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "haveged"
        
- name: HTTP-6640 Install Apache mod_evasive, HTTP-6643 Install Apache modsecurity
  package:
    name:
      - libapache2-mod-evasive
      - libapache2-mod-security2
    state: present
  notify:
    - restart apache2
