---
# handlers file for lynis-role

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted    

- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: restart ntp
  service:
    name: ntp
    state: restarted    